[package]
name = "engine-q"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reedline = { git = "https://github.com/jntrnr/reedline", branch = "main" }
nu-ansi-term = "0.32.0"
# mimalloc = { version = "*", default-features = false }

[dev-dependencies]
tempfile = "3.2.0"
assert_cmd = "1.0.7"
pretty_assertions = "0.7.2"
