[package]
name = "engine-q"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/nu-cli", "crates/nu-engine", "crates/nu-parser"]

[dependencies]
reedline = { git = "https://github.com/jntrnr/reedline", branch = "main" }
codespan-reporting = "0.11.1"
nu-cli = { path="./crates/nu-cli" }
nu-engine = { path="./crates/nu-engine" }
nu-parser = { path="./crates/nu-parser" }

# mimalloc = { version = "*", default-features = false }

[dev-dependencies]
tempfile = "3.2.0"
assert_cmd = "1.0.7"
pretty_assertions = "0.7.2"
