[package]
name = "engine-q"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reedline = {git = "https://github.com/jntrnr/reedline"}