[package]
name = "nu"
version = "0.1.1"
authors = ["Yehuda Katz <wycats@gmail.com>"]
description = "A shell for the GitHub era"
license = "ISC"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = { version = "4.0.0", git = "https://github.com/wycats/rustyline.git" } 
sysinfo = "0.8.3"
chrono = "0.4.6"
chrono-tz = "0.5.1"
derive-new = "0.5.6"
prettytable-rs = "0.8.0"
itertools = "0.8.0"
ansi_term = "0.11.0"
conch-parser = "0.1.0"
nom = "5.0.0-beta1"
subprocess = "0.1.18"
dunce = "1.0.0"
futures = "0.1.27"
futures-core = "0.2.1"
indexmap = "1.0.2"
chrono-humanize = "0.0.11"
byte-unit = "2.1.0"
ordered-float = "1.0.2"
prettyprint = "0.6.0"
