[tasks.lalrpop]
install_crate = { crate_name = "lalrpop", binary = "lalrpop", test_arg = "--help" }
command = "lalrpop"
args = ["src/parser/parser.lalrpop"]

[tasks.baseline]
dependencies = ["lalrpop"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["lalrpop"]

[tasks.run]
command = "cargo"
args = ["run", "--release"]
dependencies = ["baseline"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["baseline"]

[tasks.check]
command = "cargo"
args = ["check"]
dependencies = ["baseline"]

