[package]
name = "nu_plugin_inc"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andrés N. Robalino <andres@androbtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-protocol = { path = "../nu-protocol" }
nu-source = { path = "../nu-source" }
nu-errors = { path = "../nu-errors" }
nu-value-ext = { path = "../nu-value-ext" }
semver = "0.9.0"
indexmap = "1.3.0"

[build-dependencies]
nu-build = { version = "0.1.0", path = "../nu-build" }
