[package]
<<<<<<< HEAD
authors = ["The Nu Project Contributors"]
description = "Core values and protocols for Nushell"
edition = "2018"
license = "MIT"
name = "nu-protocol"
version = "0.43.0"

[lib]
doctest = false

[dependencies]
bigdecimal = { package = "bigdecimal", version = "0.3.0", features = ["serde"] }
byte-unit = "4.0.9"
chrono = { version="0.4.19", features=["serde"] }
chrono-humanize = "0.2.1"
derive-new = "0.5.8"
getset = "0.1.1"
indexmap = { version="1.6.1", features=["serde-1"] }
log = "0.4.14"
nu-errors = { path="../nu-errors", version = "0.43.0" }
nu-source = { path="../nu-source", version = "0.43.0" }
num-bigint = { version = "0.4.3", features = ["serde"] }
num-integer = "0.1.44"
num-traits = "0.2.14"
serde = { version="1.0", features=["derive"] }
serde_bytes = "0.11.5"

[dependencies.polars]
version = "0.17.0"
optional = true
default-features = false
features = ["docs", "zip_with", "csv-file", "temporal", "performant", "pretty_fmt", "dtype-slim", "serde", "rows", "strings", "checked_arithmetic", "object", "dtype-date", "dtype-datetime", "dtype-time"]

[features]
dataframe = ["polars"]

[build-dependencies]
=======
name = "nu-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.29"
miette = "3.0.0"
serde = {version = "1.0.130", features = ["derive"]}
chrono = { version="0.4.19", features=["serde"] }
indexmap = { version="1.7", features=["serde-1"] }
chrono-humanize = "0.2.1"
byte-unit = "4.0.9"
im = "15.0.0"
serde_json = { version = "1.0", optional = true }
nu-json = { path = "../nu-json" }
typetag = "0.1.8"
num-format = "0.4.0"
sys-locale = "0.1.0"

[features]
plugin = ["serde_json"]

[dev-dependencies]
serde_json = "1.0"
>>>>>>> 9259a56a28f1dd3a4b720ad815aa19c6eaf6adce
