[package]
authors = ["The Nu Project Contributors", "Christian Zangl <laktak@cdak.net>"]
description = "Fork of serde-hjson"
<<<<<<< HEAD
edition = "2018"
license = "MIT"
name = "nu-json"
version = "0.43.0"
=======
edition = "2021"
license = "MIT"
name = "nu-json"
version = "0.37.1"
>>>>>>> 9259a56a28f1dd3a4b720ad815aa19c6eaf6adce

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
preserve_order = ["linked-hash-map", "linked-hash-map/serde_impl"]
default = ["preserve_order"]

[dependencies]
serde = "1.0"
num-traits = "0.2.14"
regex = "^1.0"
lazy_static = "1"
linked-hash-map = { version="0.5", optional=true }

[dev-dependencies]
<<<<<<< HEAD
nu-path = { version = "0.43.0", path="../nu-path" }
nu-test-support = { version = "0.43.0", path="../nu-test-support" }
=======
nu-path = { version = "0.37.1", path="../nu-path" }
>>>>>>> 9259a56a28f1dd3a4b720ad815aa19c6eaf6adce
serde_json = "1.0.39"
