[package]
name = "nu-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
miette = { git = "https://github.com/zkat/miette", rev = "183ecb9" }
# miette = { path = "../../../miette" }
thiserror = "1.0.29"
nu-protocol = { path = "../nu-protocol"}
